matrix:
  include:
    - language: erlang
      otp_release: 20.0
      install: make deps
      script: make && make dialyze
branches:
  only:
  - gh-pages
  - /.*/
notifications:
  email:
    recipients:
      - aabbcc1241@yahoo.com.hk
    on_success: change
    on_failure: always
