matrix:
  include:
    - language: node_js
      before_script: npm install
      node_js:
        - "9"
        - "8"
        - "7"
        - "6"
        - "5"
        - "4"
        - "0.12"
branches:
  only:
  - gh-pages
  - /.*/
notifications:
  email:
    recipients:
      - aabbcc1241@yahoo.com.hk
    on_success: change
    on_failure: always
